# Generated by Django 4.2.13 on 2024-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("names", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="name",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="name",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="name",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
