# Generated by Django 4.2.13 on 2024-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("names", "0002_name_is_active_alter_name_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name_form",
                    models.CharField(max_length=100, verbose_name="Name form"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                ("description", models.TextField(max_length=3000)),
                ("image_url", models.URLField(verbose_name="Image URL")),
                ("date_of_birth", models.DateField(verbose_name="Date of birth")),
                (
                    "date_of_death",
                    models.DateField(blank=True, verbose_name="Date of death"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="name",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                default="M",
                max_length=1,
                verbose_name="Gender",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="name",
            name="likes_count",
            field=models.IntegerField(default=0, verbose_name="Likes Count"),
        ),
        migrations.AddField(
            model_name="name",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Views Count"),
        ),
        migrations.CreateModel(
            name="FamousPeople",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "occupation",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="occupations",
                        to="names.occupation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="name",
            name="famous_persons",
            field=models.ManyToManyField(
                related_name="people", to="names.famouspeople"
            ),
        ),
        migrations.AddField(
            model_name="name",
            name="forms_of_the_name",
            field=models.ManyToManyField(related_name="forms", to="names.nameform"),
        ),
    ]
