# Generated by Django 4.2.13 on 2024-06-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("names", "0003_nameform_occupation_name_gender_name_likes_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="famouspeople",
            name="occupation",
        ),
        migrations.DeleteModel(
            name="Occupation",
        ),
        migrations.AddField(
            model_name="famouspeople",
            name="occupation",
            field=models.CharField(
                default="Shoir", max_length=100, verbose_name="Occupation"
            ),
            preserve_default=False,
        ),
    ]
