# Generated by Django 4.2.13 on 2024-06-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("names", "0004_remove_famouspeople_occupation_delete_occupation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="name",
            name="famous_persons",
        ),
        migrations.RemoveField(
            model_name="name",
            name="forms_of_the_name",
        ),
        migrations.AddField(
            model_name="name",
            name="famous_persons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="names.famouspeople",
            ),
        ),
        migrations.AddField(
            model_name="name",
            name="forms_of_the_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="names.nameform",
            ),
        ),
    ]
